server:
    port: 8082
    address: localhost
spring:
    thymeleaf:
        mode: HTML
        prefix: classpath:/templates/
        suffix: .html
        enabled: true
        encoding: UTF-8
        cache: false
        content-type: text/html
        check-template-location: true
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    datasource:
        url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=utf-8&useSSL=true
        driver-class-name: com.mysql.jdbc.Driver
        username: caist
        password: caist
        type: com.alibaba.druid.pool.DruidDataSource
        filter: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 10
        maxIdle: 15
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mapper/**/*.xml
logging:
    level:
        com:
            caist: DEBUG
#pagehelper
pagehelper:
    autoDialect: true
    closeConn: true
#diy param
system:
    name: 管理系统
    defaultModule: system
